repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.11.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_docs_replace
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-added-large-files
